#!/bin/bash

COMPILER='GNU_DEBUG'

#First the bootstrapper:
git submodule init && git submodule update
./bootstrap

cd hdf5
if [[ $COMPILER == *GNU* ]]; then
  make CC="gcc" FC="gfortran"
  cd ..
  if [[ $COMPILER == *DEBUG* ]]; then
    #FOR DEBUGGING
    ./configure CFLAGS="-Wall -O0 -g" FCFLAGS="-cpp -fdefault-real-8 -fdefault-double-8 -fbackslash -g -O0 -ggdb3 -fbounds-check -finit-real=nan -fbacktrace -DGNU" --with-hdf5=hdf5/hdf5-1.8.13/hdf5  --enable-debug
  else
    #FOR OPTIMIZATION
    ./configure CFLAGS="-Wall -O2" FCFLAGS="-cpp -fdefault-real-8 -fdefault-double-8 -fbackslash -O2 " --with-hdf5=hdf5/hdf5-1.8.13/hdf5;
  fi
elif [[ $COMPILER == *INTEL* ]]; then
  make CC=icc FC=ifort
  cd ..
fi

# Compile stuff
make
